version: 1.0.{build}
image:
- Visual Studio 2017
install:
- git submodule update --init --recursive
environment:
  matrix:
  - {}
build_script:
- cmd: |
    cmake -S . -B builds -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=C:\Python36-x64)
    cmake --build builds --config Debug
    cmake --build builds --config Release
