version: 1.0.{build}
image:
- Visual Studio 2017
install:
- git submodule update --init --recursive
environment:
  matrix:
  - {}
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))  
build_script:
- cmd: |
    cmake -S . -B builds -G "Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE=C:\Python36-x64\python.exe)
    cmake --build builds --config Debug
    cmake --build builds --config Release
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
